### ISSUE TITLE
Transfer this module to voxpupuli

### ISSUE THREAD

**Issue by witjoh** [voxpupuli/puppet-wildfly#279]
@biemond Since this repo doesn't move a lot for years, is there a possibility to transfer it ot voxpupuli ?

**Comment by EmersonPrado** [comment]
@biemond Would you mind commenting on this? This module is quite useful and deserves some more traction.

**Comment by rwaffen** [comment]
Hi @biemond any opinion about this?

**Comment by biemond** [comment]
yep ok, only no time to do this all https://voxpupuli.org/docs/migrate_module/

**Comment by rwaffen** [comment]
I can assist with all the admin/moderator stuff of voxpupuli. i will add you to the migration list and so.
i also can open a pull request for module sync for you?

let me know if this might be helpful for you

**Comment by biemond** [comment]
awesome , lets do that

**Comment by rwaffen** [comment]
@biemond got any time yet to transfer the repo?

**Comment by biemond** [comment]
ah just too late , can you send me again.

**Comment by rwaffen** [comment]
okay... been there, done that :-D

**Comment by biemond** [comment]
done

**Comment by biemond** [comment]
should I transfer ownership?

**Comment by rwaffen** [comment]
yep, so that the module can become `voxpupuli/puppet-wildfly`

**Comment by rwaffen** [comment]
i also will add you to the collaborators, so that you still can manage the repo

**Comment by biemond** [comment]
done

**Comment by jairojunior** [comment]
End of an era. Feels like we got the approved badge so long ago. I am pretty sure it will be better supported by voxpupuli from now on.

**Comment by biemond** [comment]
indeed , did not do chef or puppet for a longtime and glad, people are still using puppet and app servers.

enjoy and make it better

**Comment by rwaffen** [comment]
thanks for the migration!
will handle the next steps in the coming week

**Comment by rwaffen** [comment]
transfer is completed. we will fix the code for our linters in upcoming PRs. if you are not a collaborator at voxpupuli yet, you also can become one, just mention it to me. (warning, you will recieve a lot of mails from github then XD )

**Comment by EmersonPrado** [comment]
Kudos to all!
What is still needed for the new location to appear in Forge?

**Comment by rwaffen** [comment]
i'm working on #297 and if this is done, i think i can do a release. tests have to be working first. still struggling with the acceptance tests. I can work every friday on this.

**Comment by EmersonPrado** [comment]
@rwaffen Great! Pls ping if I can be of any help. I'm not even a beginner in acceptance tests, but have been playing around quite a bit with this module.

**Comment by rwaffen** [comment]
will do! if i got all merged and have it all together you can beta test the updated module. so we might see if i broke something, which is not covered by tests
