### ISSUE TITLE
Missing template when using jboss-eap as distribution

### ISSUE THREAD

**Issue by khlnx** [voxpupuli/puppet-wildfly#337]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby: 2.0.0
- Distribution: Redhat7, Redhat9
- Module version: 3.2.0

## How to reproduce (e.g Puppet code you use)
```puppet
class { 'wildfly':
  version        => '7.3.5',
  distribution   => 'jboss-eap',
  install_source => 'http:/mywebserver/jboss-eap-7.3.5.tar.gz',
  user           => 'jboss',
  group          => 'jboss',
  dirname        => '/opt/jboss-eap',
  console_log    => '/var/log/jboss/console.log',
}
```

## What are you seeing
It seems that a template is missing for jboss, as soon as the Catalog is compiled this Error occurs both on Redhat 7 and 9:
``Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'jboss-eap/jboss-eap.systemd.service.epp' (file: /etc/puppetlabs/code/environments/khahn/modules/wildfly/manifests/service/systemd.pp, line: 23, column: 16) on node minimal7.khahn.universa.de
``

**Comment by tuxmea** [comment]
fixed in https://github.com/voxpupuli/puppet-wildfly/pull/341
